/*
 * This file is generated by jOOQ.
 */
package com.gmail.pzalejko.joo.examle.db;


import com.gmail.pzalejko.joo.examle.db.tables.FlywaySchemaHistory;
import com.gmail.pzalejko.joo.examle.db.tables.Measurement;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Dev extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>dev</code>
     */
    public static final Dev DEV = new Dev();

    /**
     * The table <code>dev.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>dev.measurement</code>.
     */
    public final Measurement MEASUREMENT = Measurement.MEASUREMENT;

    /**
     * No further instances allowed
     */
    private Dev() {
        super("dev", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            Measurement.MEASUREMENT
        );
    }
}
