/*
 * This file is generated by jOOQ.
 */
package com.gmail.pzalejko.joo.examle.db;


import com.gmail.pzalejko.joo.examle.db.tables.FlywaySchemaHistory;
import com.gmail.pzalejko.joo.examle.db.tables.Measurement;
import com.gmail.pzalejko.joo.examle.db.tables.records.FlywaySchemaHistoryRecord;
import com.gmail.pzalejko.joo.examle.db.tables.records.MeasurementRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in dev.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, DSL.name("flyway_schema_history_pk"), new TableField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
    public static final UniqueKey<MeasurementRecord> MEASUREMENT_PKEY = Internal.createUniqueKey(Measurement.MEASUREMENT, DSL.name("measurement_pkey"), new TableField[] { Measurement.MEASUREMENT.ID }, true);
}
