/*
 * This file is generated by jOOQ.
 */
package com.gmail.pzalejko.joo.examle.db;


import com.gmail.pzalejko.joo.examle.db.tables.FlywaySchemaHistory;
import com.gmail.pzalejko.joo.examle.db.tables.Measurement;


/**
 * Convenience access to all tables in dev.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>dev.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>dev.measurement</code>.
     */
    public static final Measurement MEASUREMENT = Measurement.MEASUREMENT;
}
